name: mocheffendi.hilux_sensor
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

environment:
  sdk: ">=3.0.5 <4.0.0"
  # sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus:
    ^1.14.7
    # When depending on this package from a real application you should use:
    #   flutter_blue_plus: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    # path: ../
  cupertino_icons: ^1.0.2
  permission_handler: ^10.4.3
  sleek_circular_slider: ^2.0.1
  shared_preferences: ^2.1.2
  badges: ^3.1.1
  # flutter_svg: ^2.0.7
  # home_widget: ^0.3.0
  # workmanager:
  #   git:
  #     url: https://github.com/sunalwaysknows/flutter_workmanager
  #     ref: f37742bcf612c51e9571d623138a21a90a5992ea
  fl_chart: ^0.63.0
  google_fonts: ^5.1.0
  syncfusion_flutter_gauges: ^22.1.37
  # restart_app: ^1.2.1

flutter:
  uses-material-design: true
